#!/usr/bin/env python3
"""Build the mobile-first, fact-first industrial lead view."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "customer/industrial-leads/index.html"
MANIFEST = ROOT / "customer/industrial-leads/pipeline-manifest.json"

def model():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))

def page(m):
    data = json.dumps(m, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    leads = m["leads"]
    yes = sum(x.get("stage2") == "YES" for x in leads)
    enriched = sum(x.get("stage3") == "ENRICHED" for x in leads)
    css = r'''
:root{color-scheme:light;--ink:#17212b;--muted:#657582;--line:#dbe4e9;--bg:#f3f7f8;--blue:#0e628c;--green:#176a49;--amber:#8a5a11;--red:#a13b3b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif}main{max-width:1180px;margin:auto;padding:18px}h1,h2,h3,p{margin:0}h1{font-size:clamp(25px,5vw,36px);line-height:1.2}.muted{color:var(--muted);font-size:14px}.intro{margin:5px 0 16px}.toolbar{position:sticky;top:0;z-index:2;background:rgba(243,247,248,.96);padding:8px 0 12px}.search{width:100%;border:1px solid #b9cbd4;border-radius:12px;padding:13px 14px;font:inherit;background:#fff}.stats{display:flex;gap:8px;overflow:auto;margin:12px 0}.stat{min-width:105px;background:#fff;border:1px solid var(--line);border-radius:12px;padding:9px 12px}.stat b{display:block;font-size:21px}.layout{display:grid;grid-template-columns:335px minmax(0,1fr);gap:14px;align-items:start}aside,.detail,.box{background:#fff;border:1px solid var(--line);border-radius:14px}.list{overflow:hidden;position:sticky;top:76px;max-height:calc(100vh - 92px);overflow-y:auto}.day{font-size:13px;font-weight:700;color:var(--muted);padding:10px 12px 5px;background:#f7fafb;border-bottom:1px solid #edf2f4}.row{display:block;width:100%;padding:11px 12px;text-align:left;border:0;border-bottom:1px solid #edf2f4;background:#fff;cursor:pointer;font:inherit}.row:hover,.active{background:#e9f4f8}.row b,.row span,.row small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.row b{font-size:15px}.row span{font-weight:600}.row small{color:var(--muted);font-size:13px}.detail{padding:16px}.detail-head{padding-bottom:12px;border-bottom:1px solid var(--line)}.detail h2{font-size:24px;line-height:1.25}.badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.badge{border-radius:99px;padding:4px 9px;font-size:13px;font-weight:700}.green{background:#e8f6ee;color:var(--green)}.amber{background:#fff4d9;color:var(--amber)}.red{background:#fdecec;color:var(--red)}.blue{background:#e7f1f7;color:var(--blue)}.facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:12px 0}.fact{background:#f7fafb;border-radius:10px;padding:9px 10px}.fact label{display:block;color:var(--muted);font-size:13px}.box{padding:13px;margin-top:12px}.box h3{font-size:17px;margin-bottom:7px}.box ul{margin:0;padding-left:20px}.box li+li{margin-top:7px}details{margin-top:10px}summary{cursor:pointer;font-weight:700;color:var(--blue)}a{color:var(--blue);word-break:break-all}.empty{padding:20px;color:var(--muted)}.prompt{background:#fff8e8;border-color:#e6d49f;white-space:pre-wrap;font-family:inherit;font-size:14px}
@media(max-width:760px){main{padding:12px}.layout{display:block}.list{position:static;max-height:none;margin-bottom:12px}.detail{padding:13px;scroll-margin-top:10px}.facts{grid-template-columns:1fr 1fr}.row{padding:10px 11px}.toolbar{top:0}.detail h2{font-size:22px}}
'''
    js = r'''
const d=JSON.parse(document.getElementById('data').textContent),list=document.querySelector('aside'),detail=document.querySelector('.detail'),search=document.querySelector('#search');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const status=(x,type)=>{const map={DISCOVERED:'已发现',SOURCE_NOT_LINKED:'未找到对应发现记录',NOT_RUN:'还未判断',YES:'已确认可以跟进',ENRICHED:'已完成资料补充',BLOCKED:'暂时不能补充资料'};return `<span class="badge ${type}">${esc(map[x]||x||'没有记录')}</span>`};
function renderList(){const q=search.value.trim().toLowerCase(),rows=d.leads.map((r,i)=>({r,i})).filter(({r})=>!q||JSON.stringify(r).toLowerCase().includes(q));const days=[...new Set(rows.map(x=>x.r.date))];list.innerHTML=days.length?days.map(day=>`<div class="day">${esc(day)}</div>`+rows.filter(x=>x.r.date===day).map(x=>`<button class="row" data-i="${x.i}"><b>${esc(x.r.lead.lead_id)}</b><span>${esc(x.r.lead.company?.company_name||'公司名称未记录')}</span><small>${esc(x.r.lead.project?.project_name||x.r.lead.signal?.signal_description||'项目名称未记录')}</small></button>`).join('')).join(''):'<div class="empty">没有找到匹配线索</div>';list.querySelectorAll('.row').forEach(x=>x.onclick=()=>show(+x.dataset.i,true));}
function show(i,focus=false){const r=d.leads[i],l=r.lead,z=r.stage3_result||{},ev=l.evidence||[],unknowns=z.unknowns||[];list.querySelectorAll('.row').forEach(x=>x.classList.toggle('active',+x.dataset.i===i));const evidence=ev.length?ev.map(x=>`<li><b>${esc(x.document_title||x.source_type||'来源记录')}</b><br>${esc(x.verbatim_evidence||x.evidence_summary||'没有摘录原文')}<br><a href="${esc(x.canonical_url||x.source_url||'#')}" target="_blank" rel="noreferrer">打开来源</a></li>`).join(''):'<li>没有证据记录</li>';const gap=unknowns.length?unknowns.map(x=>`<li>${esc(typeof x==='string'?x:x.description||JSON.stringify(x))}</li>`).join(''):'<li>Water Clay 没有登记未知项。</li>';const prompt=`请补充线索 ${l.lead_id}：\n1. 找到 Stage 1 原始发现记录，并确认与公司、项目、日期是否一致。\n2. 给出 Stage 2 判断：YES（可以跟进）/ REVIEW（需要人工复核）/ NO（不跟进），并写明事实依据。\n3. 如果是 YES，再补充：项目当前进度、业主/设计/施工/供应商、采购负责人或技术负责人姓名及公开联系方式。\n4. 每条信息附来源链接和原文摘录；没有找到就明确写“未找到”，不要推测。`;detail.innerHTML=`<div class="detail-head"><h2>${esc(l.company?.company_name||'公司名称未记录')}</h2><p class="muted">${esc(l.lead_id)} · ${esc(r.date)} · ${esc(l.company?.location||'地区未记录')}</p><div class="badges">${status(r.stage1,'blue')}${status(r.stage2,r.stage2==='YES'?'green':'amber')}${status(r.stage3,r.stage3==='ENRICHED'?'green':'red')}</div></div><div class="facts"><div class="fact"><label>项目</label>${esc(l.project?.project_name||'未记录')}</div><div class="fact"><label>当前进度（记录值）</label>${esc(l.project?.project_stage||z.main_project_stage?.value||'未记录')}</div><div class="fact"><label>线索来源日期</label>${esc(l.signal?.signal_date||r.date||'未记录')}</div><div class="fact"><label>证据条数</label>${ev.length} 条</div></div><div class="box"><h3>现在能确认的事实</h3><p>${esc(l.signal?.signal_description||'没有信号描述')}</p><p class="muted">${esc(r.stage3_detail||r.stage2_detail||'没有补充说明')}</p></div><details class="box" open><summary>查看来源证据（${ev.length} 条）</summary><ul>${evidence}</ul></details><details class="box"><summary>查看缺口</summary><ul>${r.stage1==='SOURCE_NOT_LINKED'?'<li>这条记录没有找到对应的 Stage 1 原始发现记录。</li>':''}${r.stage2!=='YES'?'<li>没有这条 Lead ID 的 Stage 2 明确判断，因此不能确认是否值得跟进。</li>':''}${r.stage3!=='ENRICHED'?'<li>没有 Stage 3 补充结果；原因是 Stage 2 尚未明确为“可以跟进”。</li>':''}${gap}</ul></details><details class="box prompt"><summary>给工业雷达的补充要求（可复制）</summary>${esc(prompt)}</details>`;if(focus)detail.scrollIntoView({behavior:'smooth',block:'start'});}
search.oninput=renderList;renderList();show(0);
'''
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f3f7f8"><title>工业线索</title><style>{css}</style></head><body><main><p class="muted">IMS GTM · 销售线索</p><h1>工业线索</h1><p class="intro muted">按日期找线索。页面只显示资料里已经写明的事实。</p><div class="toolbar"><input id="search" class="search" aria-label="搜索线索" placeholder="搜索公司、项目或线索编号…"></div><div class="stats"><div class="stat"><b>{len(leads)}</b><span>全部线索</span></div><div class="stat"><b>{yes}</b><span>已确认可跟进</span></div><div class="stat"><b>{enriched}</b><span>已补充资料</span></div></div><div class="layout"><aside class="list" aria-label="线索列表"></aside><section class="detail" aria-live="polite"></section></div><p class="muted" style="margin-top:12px">资料负责人：国内团队 · 本页不自动猜测、不自动改变线索状态</p></main><script id="data" type="application/json">{data}</script><script>{js}</script></body></html>'''

if __name__ == "__main__":
    m = model()
    PAGE.parent.mkdir(parents=True, exist_ok=True)
    PAGE.write_text(page(m), encoding="utf-8")
    print(f"Built mobile fact-first page for {len(m['leads'])} records")
